-- 1. Add new columns to PROFILES if they don't exist
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'avatar_url') then
        alter table public.profiles add column avatar_url text;
    end if;
    if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'banner_url') then
        alter table public.profiles add column banner_url text;
    end if;
end $$;

-- 2. Add new columns to PRODUCTS if they don't exist
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'thumbnail_url') then
        alter table public.products add column thumbnail_url text;
    end if;
end $$;

-- 3. Create QNA table if it doesn't exist
create table if not exists public.qna (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) not null,
  user_id uuid references public.profiles(id) not null,
  question text not null,
  answer text, -- Filled by seller/admin
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS on QNA (idempotent)
alter table public.qna enable row level security;

-- 5. Create Policies for QNA (drop first to avoid error if exists)
drop policy if exists "Q&A viewable by everyone." on qna;
create policy "Q&A viewable by everyone." on qna for select using ( true );

drop policy if exists "Users can ask questions." on qna;
create policy "Users can ask questions." on qna for insert with check ( auth.uid() = user_id );

drop policy if exists "Sellers can answer questions." on qna;
create policy "Sellers can answer questions." on qna for update using ( 
  exists (select 1 from products where id = qna.product_id and seller_id = auth.uid()) or
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
