-- Add cart_items table for persistent user carts
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  product_id bigint references public.products(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- Enable RLS
alter table public.cart_items enable row level security;

-- Policies
drop policy if exists "Users can view their own cart items." on cart_items;
create policy "Users can view their own cart items." 
  on cart_items for select 
  using ( auth.uid() = user_id );

drop policy if exists "Users can add to their cart." on cart_items;
create policy "Users can add to their cart." 
  on cart_items for insert 
  with check ( auth.uid() = user_id );

drop policy if exists "Users can delete from their cart." on cart_items;
create policy "Users can delete from their cart." 
  on cart_items for delete 
  using ( auth.uid() = user_id );
