-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, service_role;

-- PROFILES (Extends Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text,
  role text default 'buyer' check (role in ('buyer', 'seller', 'admin')),
  balance decimal(10, 2) default 0.00,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- PRODUCTS
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price decimal(10, 2) not null,
  platform text not null, -- 'Steam', 'Xbox', etc.
  region text not null, -- 'Global', 'US', etc.
  stock_count int default 0,
  image_url text,
  seller_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.products enable row level security;

create policy "Products are viewable by everyone."
  on products for select
  using ( true );

create policy "Sellers and Admins can insert products."
  on products for insert
  with check ( 
    auth.uid() in (select id from profiles where role in ('seller', 'admin'))
  );

create policy "Sellers and Admins can update their products."
  on products for update
  using ( 
    auth.uid() = seller_id or 
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- ORDERS
create table public.orders (
  id bigint generated by default as identity primary key,
  buyer_id uuid references public.profiles(id) not null,
  product_id bigint references public.products(id) not null,
  status text default 'completed',
  key_value text, -- The digital key delivered
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;

create policy "Users can see their own orders."
  on orders for select
  using ( auth.uid() = buyer_id );

create policy "Admins can see all orders."
  on orders for select
  using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );

create policy "Users can create orders."
  on orders for insert
  with check ( auth.uid() = buyer_id );
